### PR TITLE
Add OpenBSD support

### PR DESCRIPTION
**Pull request by jturner**
This takes care of https://github.com/intel/ittapi/issues/65. I'm able to `buildall.py` and `cargo build --release` after these changes.

### CODE REVIEW

**Comment by seanm** [comment]
@jturner could you rebase this to fix conflicts?

**Comment by jturner** [comment]
> @jturner could you rebase this to fix conflicts?

@seanm Should be good to go.

**Comment by seanm** [comment]
@jturner hey thanks for that!  Looks like maybe you should squash those 2 commits?

**Comment by jturner** [comment]
> @jturner hey thanks for that! Looks like maybe you should squash those 2 commits?

Good call. Done!

**Pull request merged**
